# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import YOLOsvc_pb2 as YOLOsvc__pb2


class YOLOsvcStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObjectDetection = channel.unary_unary(
                '/YOLOsvc.YOLOsvc/ObjectDetection',
                request_serializer=YOLOsvc__pb2.Image.SerializeToString,
                response_deserializer=YOLOsvc__pb2.Detections.FromString,
                )
        self.ObjectDetectionV2 = channel.unary_unary(
                '/YOLOsvc.YOLOsvc/ObjectDetectionV2',
                request_serializer=YOLOsvc__pb2.ImageB64.SerializeToString,
                response_deserializer=YOLOsvc__pb2.Detections.FromString,
                )


class YOLOsvcServicer(object):
    """Interface exported by the server.
    """

    def ObjectDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObjectDetectionV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YOLOsvcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObjectDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.ObjectDetection,
                    request_deserializer=YOLOsvc__pb2.Image.FromString,
                    response_serializer=YOLOsvc__pb2.Detections.SerializeToString,
            ),
            'ObjectDetectionV2': grpc.unary_unary_rpc_method_handler(
                    servicer.ObjectDetectionV2,
                    request_deserializer=YOLOsvc__pb2.ImageB64.FromString,
                    response_serializer=YOLOsvc__pb2.Detections.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YOLOsvc.YOLOsvc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YOLOsvc(object):
    """Interface exported by the server.
    """

    @staticmethod
    def ObjectDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YOLOsvc.YOLOsvc/ObjectDetection',
            YOLOsvc__pb2.Image.SerializeToString,
            YOLOsvc__pb2.Detections.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObjectDetectionV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/YOLOsvc.YOLOsvc/ObjectDetectionV2',
            YOLOsvc__pb2.ImageB64.SerializeToString,
            YOLOsvc__pb2.Detections.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
